In [2]:
import numpy as np

a = np.random.random(10)
b = np.random.random((2,3))
print(a)
print(b)

[0.61205885 0.54053957 0.8482905  0.55012311 0.55753731 0.16491622
 0.40004413 0.48585435 0.47101495 0.07082539]
[[0.88296331 0.98327471 0.17279668]
 [0.57297063 0.77089343 0.45527891]]


In [10]:
a = np.random.randint(5,size=5)
b = np.random.randint(5,size=(2,3))
print(a)
print(b)

[1 3 0 1 1]
[[2 1 4]
 [1 0 4]]


In [9]:
# 标准正态分布
a = np.random.randn(5)
b = np.random.randn(2,3)
print(a)
print(b)

[ 0.25332489  0.48297208 -0.12446436 -0.06632286  0.62971503]
[[ 0.7103428   1.37511726 -0.08315289]
 [-1.80334548 -2.17747635 -1.14070498]]


In [12]:
# 指定正态分布
a = np.random.normal(loc=5,scale=6,size=(2,3))
print(a)

[[ 5.25059486  5.13103382 -3.42707782]
 [-0.24041593 -0.8642572  -3.89405017]]
