In [9]:
import numpy as np

a = np.zeros((3,4))
b = np.zeros(5)
print(a)
print(b)

c = np.zeros_like(a)    # 创建一个与a相同shape的数组
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
a = np.ones((3,4),dtype=int)
print(a)

b = np.ones_like(a)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
# 未初始化的数组
# 数组内的数组是随机的
a = np.empty((3,4))
print(a)

b = np.empty_like(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
a = np.full((3,4),fill_value=5)
print(a)

b = np.full_like(a,fill_value=6)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [29]:
# 创建单位矩阵
a = np.eye(3)
print(a)

# M是列数 
b = np.eye(3,M=4)
print(b)

# k是指定对角线位置的
c = np.eye(4,5,2)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
