In [17]:
import numpy as np

# 一维数组
a = np.arange(10)
print(a)
print(a[:])
print(a[2])
print(a[2:5])
print(a[::-1])
print(a[-2:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
2
[2 3 4]
[9 8 7 6 5 4 3 2 1 0]
[8 9]


In [33]:
# 二维数组
'''
Axis 0 ——> 行索引,从上往下
Axis 1 ——> 列索引,从左往右
'''
x = np.arange(1,13)
a = np.reshape(x,(4,3))
print(a)
print('第二行:',a[1])
print('二行三列:',a[1,2])   # a[1][2]
print('每行第二列:',a[:,1])
print('奇数行的第一列:',a[::2,0])
print('偶数行的第一列:',a[1::2,0])
print('第三行第二列和第四行第一列:',a[(2,3),(1,0)])
print('第一行和第二行的前两列:\n',a[0:2,0:2])
print('倒序:\n',a[::-1,::-1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
第二行: [4 5 6]
二行三列: 6
每行第二列: [ 2  5  8 11]
奇数行的第一列: [1 7]
偶数行的第一列: [ 4 10]
第三行第二列和第四行第一列: [ 8 10]
第一行和第二行的前两列:
 [[1 2]
 [4 5]]
倒序:
 [[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


In [ ]:
# 切片数组的复制
'''
numpy中的copy()是深拷贝
'''