In [1]:
import numpy as np

a = np.arange(1,13)
print(a)

b = np.reshape(a,(3,4))
print(b)

c = np.reshape(b,-1)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


ravel() 返回的是视图,会影响原始数组

In [2]:
print(b)
a1 = b.ravel()
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
a1[0] = 1000
print(a1)
print(b)

[1000    2    3    4    5    6    7    8    9   10   11   12]
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]


flatten() 返回的是拷贝,对拷贝所做的修改不会影响原始数组

In [8]:
a = np.arange(1,13).reshape(3,4)
print(a)

b = a.flatten()
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
b[0] = 1000
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1000    2    3    4    5    6    7    8    9   10   11   12]
