In [6]:
import numpy as np

a = np.arange(1,4)
b = np.arange(4,7)
c = np.concatenate((a,b))
print(c)
# 都是一维数组,只有一个方向的Axis

[1 2 3 4 5 6]


In [12]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
c = np.concatenate((a,b))
d = np.concatenate((a,b),axis=1)
print(c)
print(d)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


hstack()和vstack()的使用

In [14]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
c = np.hstack((a,b))
d = np.vstack((a,b))
print(c)
print(d)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
