In [2]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
print(a)
b = a.transpose()
print(b)
c = a.T
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


split、hsplit、vsplit

In [8]:
a = np.arange(1,17)
b = np.split(a,4)
c = np.split(a,[3,5])   # 以索引3、5的位置进行分隔
print(b)
print(c)


[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12]), array([13, 14, 15, 16])]
[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])]


In [18]:
a = np.arange(1,17).reshape(4,4)
b = np.hsplit(a,2)
c = np.hsplit(a,[1,3])
# b
c

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [20]:
a = np.arange(1,17).reshape(4,4)
b = np.vsplit(a,2)
c = np.vsplit(a,[1,3])
# b
c

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]