In [4]:
import numpy as np

a = np.arange(1,10,dtype=float)
print(np.reciprocal(a))  # 倒数
print(np.square(a))      # 平方
print(np.sign(a))        # 计算各元素的符号,1(正数),0(零),-1(负数)


[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]
[ 1.  4.  9. 16. 25. 36. 49. 64. 81.]
[ 1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [6]:
a = np.array([1.0,4.55, 123, 0.567, 25.532,-1.414])
print(np.around(a))
# print(np.ceil(a))     向上取整
# print(np.floor(a))    向下取整

[  1.   5. 123.   1.  26.  -1.]
[  1.   5. 123.   1.  26.  -1.]
[  1.   4. 123.   0.  25.  -2.]


In [15]:
a = np.arange(1,10,dtype=float).reshape(3,3)
b = np.array([8,9,10])
print(a)
print(np.add(a,b))
print('-------------------------')
print(np.subtract(a,b))
print('-------------------------')
print(np.multiply(a,b))
print('-------------------------')
print(np.divide(a,b))


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 9. 11. 13.]
 [12. 14. 16.]
 [15. 17. 19.]]
-------------------------
[[-7. -7. -7.]
 [-4. -4. -4.]
 [-1. -1. -1.]]
-------------------------
[[ 8. 18. 30.]
 [32. 45. 60.]
 [56. 72. 90.]]
-------------------------
[[0.125      0.22222222 0.3       ]
 [0.5        0.55555556 0.6       ]
 [0.875      0.88888889 0.9       ]]


In [16]:
a=np.array([10,10,30])
b=np.array([3,5,7])
print(np.mod(a,b))
print(a%b)

[1 0 2]
[1 0 2]
