In [ ]:
'''
np.sum()	求和
np.prod()	所有元素相乘
np.mean()	平均值
np.std()	标准差
np.var()	方差
np.median()	中数
np.power()	幂运算
np.sqrt()	开方
np.min()	最小值
np.max()	最大值
np.argmin()	最小值的下标
np.argmax()	最大值的下标
np.ptp()	计算一组数中最大值与最小值的差，可指定轴
np.unique()	删除数组中的重复数据，并对数据进行排序
np.nonzero()	返回数组中非零元素的索引
'''

In [2]:
import numpy as np

x = np.arange(1,5)
y = np.empty_like(x)
print(y)
np.power(x, 2, out=y)
print(y)

[ 1722778750  1851457775 -1018845203  -163876197]
[ 1  4  9 16]


In [4]:
a=np.arange(1,11).reshape(2,5)

print(np.mean(a))

print(np.mean(a,axis=0))

print(np.mean(a,axis=1))


5.5
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]
