In [1]:
import numpy as np

a = np.array([5,2,4,6,1,9])
print(a)
print(np.sort(a))
print(np.argsort(a))

[5 2 4 6 1 9]
[1 2 4 5 6 9]
[4 1 2 0 3 5]


In [2]:
a = np.array([
       [10, 35, 39, 43, 76, 47],
       [62, 61, 90, 30, 25, 99],
       [79, 89, 60,  0, 42, 77],
       [82, 83, 33, 97, 63,  6]
       ])
print(a)
print('-----------------------------')
print('axis=0:\n',np.sort(a,axis=0))
print('-----------------------------')
print('axis=1:\n',np.sort(a,axis=1))

[[10 35 39 43 76 47]
 [62 61 90 30 25 99]
 [79 89 60  0 42 77]
 [82 83 33 97 63  6]]
-----------------------------
axis=0:
 [[10 35 33  0 25  6]
 [62 61 39 30 42 47]
 [79 83 60 43 63 77]
 [82 89 90 97 76 99]]
-----------------------------
axis=1:
 [[10 35 39 43 47 76]
 [25 30 61 62 90 99]
 [ 0 42 60 77 79 89]
 [ 6 33 63 82 83 97]]


In [6]:
a = np.array([
       [10, 35, 39, 43, 76, 47],
       [62, 61, 90, 30, 25, 99],
       [79, 89, 60,  0, 42, 77],
       [82, 83, 33, 97, 63,  6]
       ])

b = a[:,3]
index = np.argsort(b)
print(index)
print(a[index])
'''
花式索引(Fancy Indexing)
在 NumPy 中,当你使用一个整数数组来索引另一个数组时,
你会得到一个新数组,其内容是用索引数组中的索引从被索引数组中选取的元素。这和传统的切片操作不同。
当你执行 a[index] 时，你实际上是在告诉 NumPy:给我一个新的数组,其
行的顺序应该与 index 数组中的索引顺序相匹配。
'''

[2 1 0 3]
[[79 89 60  0 42 77]
 [62 61 90 30 25 99]
 [10 35 39 43 76 47]
 [82 83 33 97 63  6]]
