In [1]:
import numpy as np
# numpy 中的广播机制(Broadcast)旨在解决不同形状数组之间的算术运算问题

a = np.array([1,2,3,4,5,6])
print(a+5)

[ 6  7  8  9 10 11]


In [2]:
a = np.array([
      [ 0, 0, 0],
      [10,10,10],
      [20,20,20],
      [30,30,30]
      ])
b = np.array([1,2,3])
print(a+b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [4]:
c=np.arange(3)
d=np.arange(3).reshape(3,1)
print(c)
print(d)
print('-------------------')
print(c+d)

[0 1 2]
[[0]
 [1]
 [2]]
-------------------
[[0 1 2]
 [1 2 3]
 [2 3 4]]
